server:
  port: 8080

spring:
  # 当前默认使用本地配置（可以用启动参数覆盖）
  profiles:
    active: local

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 你自己的业务配置也可以放这里（公共部分）
app:
  env: ${spring.profiles.active}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html