spring:
  datasource:
    url: jdbc:mysql://gz-cdb-h2sj5wll.sql.tencentcdb.com:21050/triaura?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 9xAeqVXg5_DxQg
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true